language: php

php:
  - 5.5
addons:
  code_climate:
    repo_token: 70178a62c87d2bc3bde881b0e10ed731144318759e5d2de1ede97cb75997b009

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - phpunit
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter